version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017"
    volumes:
      - ./data/db:/data/db

  db-exporter:
      image: bitnami/mongodb-exporter:0.11
      environment:
        - MONGODB_URI=mongodb://mongodb:27017
      restart: always
      ports: 
        - 9216:9216

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 20s
      retries: 5
  
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway.dockerfile
    env_file: ./.env
    ports:
      - 3010:3010
    volumes:
      - /api-gateway:/api-gateway
      - /public/uploads:/app/public/uploads
    environment:
      api-gateway_URL: ${api-gateway_URL}
      api-gateway_PORT: ${api-gateway_PORT}
      auth-service_URL: ${auth-service_URL}
      auth-service_PORT: ${auth-service_PORT}
      target-service_URL: ${target-service_URL}
      target-service_PORT: ${target-service_PORT}
      external-service_URL: ${external-service_URL}
      external-service_PORT: ${external-service_PORT}
      OPAQUE_TOKEN: ${OPAQUE_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      auth-service_DB: ${auth-service_DB}
      target-service_DB: ${target-service_DB}
      external-service_DB: ${external-service_DB}
      RABBIT_MQ: ${RABBIT_MQ}
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
      auth-service:
        condition: service_started
      target-service:
        condition: service_started
      external-service:
        condition: service_started
    restart: on-failure

  auth-service:
    build:
      context: .
      dockerfile: auth-service.dockerfile
    env_file: ./.env
    ports:
      - 3001:3001
    volumes:
      - /auth-service:/auth-service
      - /public/uploads:/app/public/uploads
    environment:
      api-gateway_URL: ${api-gateway_URL}
      api-gateway_PORT: ${api-gateway_PORT}
      auth-service_URL: ${auth-service_URL}
      auth-service_PORT: ${auth-service_PORT}
      target-service_URL: ${target-service_URL}
      target-service_PORT: ${target-service_PORT}
      external-service_URL: ${external-service_URL}
      external-service_PORT: ${external-service_PORT}
      OPAQUE_TOKEN: ${OPAQUE_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      auth-service_DB: ${auth-service_DB}
      target-service_DB: ${target-service_DB}
      external-service_DB: ${external-service_DB}
      RABBIT_MQ: ${RABBIT_MQ}
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    restart: on-failure

  target-service:
    build:
      context: .
      dockerfile: target-service.dockerfile
    env_file: ./.env
    ports:
      - 3002:3002
    volumes:
      - /target-service:/target-service
      - /public/uploads:/app/public/uploads
    environment:
      api-gateway_URL: ${api-gateway_URL}
      api-gateway_PORT: ${api-gateway_PORT}
      auth-service_URL: ${auth-service_URL}
      auth-service_PORT: ${auth-service_PORT}
      target-service_URL: ${target-service_URL}
      target-service_PORT: ${target-service_PORT}
      external-service_URL: ${external-service_URL}
      external-service_PORT: ${external-service_PORT}
      OPAQUE_TOKEN: ${OPAQUE_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      auth-service_DB: ${auth-service_DB}
      target-service_DB: ${target-service_DB}
      external-service_DB: ${external-service_DB}
      RABBIT_MQ: ${RABBIT_MQ}
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    restart: on-failure

  external-service:
    build:
      context: .
      dockerfile: external-service.dockerfile
    env_file: ./.env
    ports:
      - 3003:3003
    volumes:
      - /external-service:/external-service
      - /public/uploads:/app/public/uploads
    environment:
      api-gateway_URL: ${api-gateway_URL}
      api-gateway_PORT: ${api-gateway_PORT}
      auth-service_URL: ${auth-service_URL}
      auth-service_PORT: ${auth-service_PORT}
      target-service_URL: ${target-service_URL}
      target-service_PORT: ${target-service_PORT}
      external-service_URL: ${external-service_URL}
      external-service_PORT: ${external-service_PORT}
      OPAQUE_TOKEN: ${OPAQUE_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      auth-service_DB: ${auth-service_DB}
      target-service_DB: ${target-service_DB}
      external-service_DB: ${external-service_DB}
      RABBIT_MQ: ${RABBIT_MQ}
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    restart: on-failure

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
      auth-service:
        condition: service_started
      target-service:
        condition: service_started
      external-service:
        condition: service_started
    restart: on-failure
    
  grafana:
    build: ./grafana
    ports:
      - 3000:3000
    depends_on:
      prometheus:
        condition: service_started
    restart: on-failure

volumes:
  prometheus-data: