version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017"
    volumes:
      - ./data/db:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
  
  api_gateway:
    build:
      context: .
      dockerfile: api_gateway.dockerfile
    command: sh -c "npm install && npm run api_gateway"
    ports:
      - 3000:3000
    volumes:
      - /api_gateway:/api_gateway
      - /public:/public
    environment:
      - API_GATEWAY_URL=http://127.0.0.1:3000
      - API_GATEWAY_PORT=3000
      - AUTH_SERVICE_URL=http://127.0.0.1:3001
      - AUTH_SERVICE_PORT=3001
      - TARGET_SERVICE_URL=http://127.0.0.1:3002
      - TARGET_SERVICE_PORT=3002
      - EXTERNAL_SERVICE_URL=http://127.0.0.1:3003
      - EXTERNAL_SERVICE_PORT=3003
      - OPAQUE_TOKEN=0681275556
      - JWT_SECRET=melsslaapritme
      - AUTH_SERVICE_DB=mongodb://127.0.0.1:27017/auth
      - TARGET_SERVICE_DB=mongodb://127.0.0.1:27017/target
      - EXTERNAL_SERVICE_DB=mongodb://127.0.0.1:27017/external
      - RABBIT_MQ=amqp://127.0.0.1:5672
      - QUEUE_EXPOSE_TAG=exposeTag
      - QUEUE_EXPOSE_TARGET=exposeTarget
    depends_on:
      rabbitmq:
        condition: service_healthy
      - mongo
      - auth_service
      - target_service
      - external_service
    restart: on-failure

  auth_service:
    build:
      context: .
      dockerfile: auth_service.dockerfile
    command: sh -c "npm install && npm run auth_service"
    ports:
      - 3001:3001
    volumes:
      - /auth-service:/auth_service
      - /public:/public
    environment:
      - API_GATEWAY_URL=http://127.0.0.1:3000
      - API_GATEWAY_PORT=3000
      - AUTH_SERVICE_URL=http://127.0.0.1:3001
      - AUTH_SERVICE_PORT=3001
      - TARGET_SERVICE_URL=http://127.0.0.1:3002
      - TARGET_SERVICE_PORT=3002
      - EXTERNAL_SERVICE_URL=http://127.0.0.1:3003
      - EXTERNAL_SERVICE_PORT=3003
      - OPAQUE_TOKEN=0681275556
      - JWT_SECRET=melsslaapritme
      - AUTH_SERVICE_DB=mongodb://127.0.0.1:27017/auth
      - TARGET_SERVICE_DB=mongodb://127.0.0.1:27017/target
      - EXTERNAL_SERVICE_DB=mongodb://127.0.0.1:27017/external
      - RABBIT_MQ=amqp://127.0.0.1:5672
      - QUEUE_EXPOSE_TAG=exposeTag
      - QUEUE_EXPOSE_TARGET=exposeTarget
    depends_on:
      - mongo
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  target_service:
    build:
      context: .
      dockerfile: target_service.dockerfile
    command: sh -c "npm install && npm run target_service"
    ports:
      - 3002:3002
    volumes:
      - /target-service:/target_service
      - /public:/public
    environment:
      - API_GATEWAY_URL=http://127.0.0.1:3000
      - API_GATEWAY_PORT=3000
      - AUTH_SERVICE_URL=http://127.0.0.1:3001
      - AUTH_SERVICE_PORT=3001
      - TARGET_SERVICE_URL=http://127.0.0.1:3002
      - TARGET_SERVICE_PORT=3002
      - EXTERNAL_SERVICE_URL=http://127.0.0.1:3003
      - EXTERNAL_SERVICE_PORT=3003
      - OPAQUE_TOKEN=0681275556
      - JWT_SECRET=melsslaapritme
      - AUTH_SERVICE_DB=mongodb://127.0.0.1:27017/auth
      - TARGET_SERVICE_DB=mongodb://127.0.0.1:27017/target
      - EXTERNAL_SERVICE_DB=mongodb://127.0.0.1:27017/external
      - RABBIT_MQ=amqp://127.0.0.1:5672
      - QUEUE_EXPOSE_TAG=exposeTag
      - QUEUE_EXPOSE_TARGET=exposeTarget
    depends_on:
      - mongo
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  external_service:
    build:
      context: .
      dockerfile: external_service.dockerfile
    command: sh -c "npm install && npm run external_service"
    ports:
      - 3003:3003
    volumes:
      - /external-service:/external_service
      - /public:/public
    environment:
      - API_GATEWAY_URL=http://127.0.0.1:3000
      - API_GATEWAY_PORT=3000
      - AUTH_SERVICE_URL=http://127.0.0.1:3001
      - AUTH_SERVICE_PORT=3001
      - TARGET_SERVICE_URL=http://127.0.0.1:3002
      - TARGET_SERVICE_PORT=3002
      - EXTERNAL_SERVICE_URL=http://127.0.0.1:3003
      - EXTERNAL_SERVICE_PORT=3003
      - OPAQUE_TOKEN=0681275556
      - JWT_SECRET=melsslaapritme
      - AUTH_SERVICE_DB=mongodb://127.0.0.1:27017/auth
      - TARGET_SERVICE_DB=mongodb://127.0.0.1:27017/target
      - EXTERNAL_SERVICE_DB=mongodb://127.0.0.1:27017/external
      - RABBIT_MQ=amqp://127.0.0.1:5672
      - QUEUE_EXPOSE_TAG=exposeTag
      - QUEUE_EXPOSE_TARGET=exposeTarget
    depends_on:
      - mongo
      rabbitmq:
        condition: service_healthy
    restart: on-failure